window.LETTERLAB_DATA = {
  // Basisadres van data.js. Zo vinden subapps dezelfde gedeelde audiomap.
  baseUrl: new URL(".", document.currentScript.src).href,
  // De dicteewoorden waarmee een nieuwe gebruiker start.
  // 'missing' bevat de posities die de cursist zelf moet typen.
  questions: [
    { word: "kip", graphemes: ["k", "i", "p"], missing: [1] },
    { word: "maan", graphemes: ["m", "aa", "n"], missing: [1] },
    { word: "vis", graphemes: ["v", "i", "s"], missing: [1] },
    { word: "boek", graphemes: ["b", "oe", "k"], missing: [1] },
    { word: "raam", graphemes: ["r", "aa", "m"], missing: [1] },
  ],

  // Gecontroleerde woorden waaruit de generator mag kiezen.
  wordBank: [
    "bal",
    "bam",
    "ban",
    "bas",
    "bed",
    "been",
    "bek",
    "bel",
    "bes",
    "boek",
    "boom",
    "bos",
    "bus",
    "dak",
    "dam",
    "das",
    "dik",
    "doek",
    "doos",
    "duim",
    "gat",
    "haan",
    "hek",
    "hen",
    "jas",
    "kam",
    "kan",
    "kat",
    "kin",
    "kip",
    "koe",
    "kom",
    "kop",
    "kus",
    "lam",
    "maan",
    "man",
    "map",
    "mes",
    "mop",
    "mus",
    "nek",
    "pan",
    "pen",
    "pop",
    "raam",
    "rat",
    "rem",
    "rok",
    "rom",
    "sap",
    "sok",
    "som",
    "tak",
    "tas",
    "teen",
    "tin",
    "top",
    "van",
    "vat",
    "ver",
    "vis",
    "vos",
    "zak",
    "zin",
    "zon",
    "blad",
    "blik",
    "blok",
    "bloem",
    "bloed",
    "blus",
    "braaf",
    "brief",
    "broek",
    "bruin",
    "draak",
    "drie",
    "drop",
    "fles",
    "fluit",
    "glas",
    "glij",
    "gluur",
    "grap",
    "gras",
    "grijs",
    "groen",
    "groot",
    "klaar",
    "klein",
    "knap",
    "knie",
    "knop",
    "plan",
    "plat",
    "ploeg",
    "prik",
    "sla",
    "slak",
    "slim",
    "smaak",
    "smal",
    "snel",
    "snoep",
    "spin",
    "staf",
    "stap",
    "stel",
    "stem",
    "stok",
    "stop",
    "stoel",
    "trap",
    "trein",
    "vlag",
    "vlees",
    "vlieg",
    "vloer",
    "vraag",
    "vrij",
    "zwak",
    "zwem",
    "bank",
    "berg",
    "best",
    "dank",
    "dans",
    "denk",
    "dorp",
    "film",
    "hals",
    "hand",
    "helm",
    "help",
    "hond",
    "jurk",
    "kast",
    "kers",
    "kind",
    "lamp",
    "land",
    "melk",
    "mens",
    "mond",
    "park",
    "tent",
    "verf",
    "vers",
    "vest",
    "vink",
    "wind",
    "wolf",
    "zand",
    "schat",
    "schep",
    "schik",
    "schip",
    "schoen",
    "school",
    "schuur",
    "spleet",
    "sproet",
    "straat",
    "streep",
    "stroop",
    "struik",
  ],

  // M = medeklinker, K = klinker of klinkerteken.
  patterns: ["MKM", "MMKM", "MKMM", "MMMKM"],

  // Grafemen die een lesgever in de filter kan aanvinken.
  learnable: [
    "a",
    "aa",
    "b",
    "c",
    "d",
    "e",
    "ee",
    "f",
    "g",
    "h",
    "i",
    "ie",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "oe",
    "oo",
    "p",
    "r",
    "s",
    "t",
    "u",
    "ui",
    "v",
    "w",
    "z",
  ],
  learnedDefault: [
    "a",
    "aa",
    "b",
    "e",
    "ee",
    "i",
    "k",
    "m",
    "n",
    "oe",
    "p",
    "r",
    "s",
    "t",
    "v",
  ],

  // Kleinletter-AZERTY zoals het op het cursistenscherm verschijnt.
  keyboard: [
    ["a", "z", "e", "r", "t", "y", "u", "i", "o", "p"],
    ["q", "s", "d", "f", "g", "h", "j", "k", "l", "m"],
    ["w", "x", "c", "v", "b", "n"],
  ],

  // Begin-, kern- en eindstroken van het klik-klakboekje.
  clickBook: {
    begin: ["m", "k", "p", "r", "s", "v"],
    kern: ["a", "i", "aa", "oe", "oo", "ee"],
    einde: ["m", "k", "p", "s", "n", "t"],
  },

  // Nodig om automatisch MKM, MMKM enzovoort te herkennen.
  vowels: [
    "aa",
    "ee",
    "oo",
    "uu",
    "ie",
    "oe",
    "eu",
    "ui",
    "ei",
    "ij",
    "ou",
    "au",
    "a",
    "e",
    "i",
    "o",
    "u",
  ],

  // Langste combinaties worden in app.js altijd eerst gezocht.
  compoundGraphemes: [
    "sch",
    "oe",
    "aa",
    "ee",
    "oo",
    "uu",
    "ie",
    "ei",
    "ij",
    "ui",
    "eu",
    "ou",
    "au",
    "ng",
    "ch",
  ],

  // Tijdelijke uitspraakhulp zolang er geen eigen opname bestaat.
  soundPrompts: {
    m: "mmmm",
    k: "k",
    p: "p",
    r: "rrrr",
    s: "ssss",
    v: "vvvv",
    n: "nnnn",
    t: "t",
    a: "à",
    i: "ie",
    aa: "aa",
    oe: "oe",
    oo: "oo",
    ee: "ee",
  },

  // Vaste, vooraf ingesproken klanken.
  // Een lesgever kan deze in de app nog altijd met een eigen opname overschrijven.
  builtInAudio: {
    "sound:a": "assets/audio/klanken/a.mp3",
    "sound:aa": "assets/audio/klanken/aa.mp3",
    "sound:b": "assets/audio/klanken/b.mp3",
    "sound:d": "assets/audio/klanken/d.mp3",
    "sound:e": "assets/audio/klanken/e.mp3",
    "sound:ee": "assets/audio/klanken/ee.mp3",
    "sound:eu": "assets/audio/klanken/eu.mp3",
    "sound:f": "assets/audio/klanken/f.mp3",
    "sound:g": "assets/audio/klanken/g.mp3",
    "sound:h": "assets/audio/klanken/h.mp3",
    "sound:i": "assets/audio/klanken/i.mp3",
    "sound:ie": "assets/audio/klanken/ie.mp3",
    // 'ij' en 'ei' stellen hier dezelfde klank voor.
    // Beide knoppen spelen daarom één keer dezelfde opname af.
    "sound:ij": "assets/audio/klanken/ij-ei.mp3",
    "sound:ei": "assets/audio/klanken/ij-ei.mp3",
    "sound:j": "assets/audio/klanken/j.mp3",
    "sound:l": "assets/audio/klanken/l.mp3",
    "sound:m": "assets/audio/klanken/m.mp3",
    "sound:n": "assets/audio/klanken/n.mp3",
    "sound:ng": "assets/audio/klanken/ng.mp3",
    "sound:nk": "assets/audio/klanken/nk.mp3",
    "sound:o": "assets/audio/klanken/o.mp3",
    "sound:oe": "assets/audio/klanken/oe.mp3",
    "sound:oo": "assets/audio/klanken/oo.mp3",
    "sound:p": "assets/audio/klanken/p.mp3",
    "sound:r": "assets/audio/klanken/rollende_r.mp3",
    "sound:s": "assets/audio/klanken/s.mp3",
    "sound:sch": "assets/audio/klanken/sch.mp3",
    "sound:sl": "assets/audio/klanken/sl.mp3",
    "sound:sp": "assets/audio/klanken/sp.mp3",
    "sound:st": "assets/audio/klanken/st.mp3",
    "sound:t": "assets/audio/klanken/t.mp3",
    "sound:u": "assets/audio/klanken/u.mp3",
    "sound:ui": "assets/audio/klanken/ui.mp3",
    "sound:uu": "assets/audio/klanken/uu.mp3",
    "sound:v": "assets/audio/klanken/v.mp3",
    "sound:w": "assets/audio/klanken/w.mp3",
    "sound:z": "assets/audio/klanken/z.mp3",
    // 'ou' en 'au' stellen hier dezelfde klank voor.
    // Beide knoppen spelen daarom één keer dezelfde opname af.
    "sound:ou": "assets/audio/klanken/ou.mp3",
    "sound:au": "assets/audio/klanken/ou.mp3",
  },
};
