window.LETTERLAB_DATA = {
  // Basisadres van data.js. Zo vinden subapps dezelfde gedeelde audiomap.
  baseUrl: new URL(".", document.currentScript.src).href,
  // De dicteewoorden waarmee een nieuwe gebruiker start.
  // 'missing' bevat de posities die de cursist zelf moet typen.
  questions: [
    { word: "kip", graphemes: ["k", "i", "p"], missing: [1] },
    { word: "maan", graphemes: ["m", "aa", "n"], missing: [1] },
    { word: "vis", graphemes: ["v", "i", "s"], missing: [1] },
    { word: "boek", graphemes: ["b", "oe", "k"], missing: [1] },
    { word: "raam", graphemes: ["r", "aa", "m"], missing: [1] },
  ],

  // Gecontroleerde woorden waaruit de generator mag kiezen.
  wordBank: [
    "bal",
    "bam",
    "ban",
    "bas",
    "bed",
    "been",
    "bek",
    "bel",
    "bes",
    "boek",
    "boom",
    "bos",
    "bus",
    "dak",
    "dam",
    "das",
    "dik",
    "doek",
    "doos",
    "duim",
    "gat",
    "haan",
    "hek",
    "hen",
    "jas",
    "kam",
    "kan",
    "kat",
    "kin",
    "kip",
    "koe",
    "kom",
    "kop",
    "kus",
    "lam",
    "maan",
    "man",
    "map",
    "mes",
    "mop",
    "mus",
    "nek",
    "pan",
    "pen",
    "pop",
    "raam",
    "rat",
    "rem",
    "rok",
    "rom",
    "sap",
    "sok",
    "som",
    "tak",
    "tas",
    "teen",
    "tin",
    "top",
    "van",
    "vat",
    "ver",
    "vis",
    "vos",
    "zak",
    "zin",
    "zon",
    "blad",
    "blik",
    "blok",
    "bloem",
    "bloed",
    "blus",
    "braaf",
    "brief",
    "broek",
    "bruin",
    "draak",
    "drie",
    "drop",
    "fles",
    "fluit",
    "glas",
    "glij",
    "gluur",
    "grap",
    "gras",
    "grijs",
    "groen",
    "groot",
    "klaar",
    "klein",
    "knap",
    "knie",
    "knop",
    "plan",
    "plat",
    "ploeg",
    "prik",
    "sla",
    "slak",
    "slim",
    "smaak",
    "smal",
    "snel",
    "snoep",
    "spin",
    "staf",
    "stap",
    "stel",
    "stem",
    "stok",
    "stop",
    "stoel",
    "trap",
    "trein",
    "vlag",
    "vlees",
    "vlieg",
    "vloer",
    "vraag",
    "vrij",
    "zwak",
    "zwem",
    "bank",
    "berg",
    "best",
    "dank",
    "dans",
    "denk",
    "dorp",
    "film",
    "hals",
    "hand",
    "helm",
    "help",
    "hond",
    "jurk",
    "kast",
    "kers",
    "kind",
    "lamp",
    "land",
    "melk",
    "mens",
    "mond",
    "park",
    "tent",
    "verf",
    "vers",
    "vest",
    "vink",
    "wind",
    "wolf",
    "zand",
    "schat",
    "schep",
    "schik",
    "schip",
    "schoen",
    "school",
    "schuur",
    "spleet",
    "sproet",
    "straat",
    "streep",
    "stroop",
    "struik",
  ],

  // M = medeklinker, K = klinker of klinkerteken.
  patterns: ["MKM", "MMKM", "MKMM", "MMMKM"],

  // Grafemen die een lesgever in de filter kan aanvinken.
  learnable: [
    "a",
    "aa",
    "b",
    "c",
    "d",
    "e",
    "ee",
    "f",
    "g",
    "h",
    "i",
    "ie",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "oe",
    "oo",
    "p",
    "r",
    "s",
    "t",
    "u",
    "ui",
    "v",
    "w",
    "z",
  ],
  learnedDefault: [
    "a",
    "aa",
    "b",
    "e",
    "ee",
    "i",
    "k",
    "m",
    "n",
    "oe",
    "p",
    "r",
    "s",
    "t",
    "v",
  ],

  // Kleinletter-AZERTY zoals het op het cursistenscherm verschijnt.
  keyboard: [
    ["a", "z", "e", "r", "t", "y", "u", "i", "o", "p"],
    ["q", "s", "d", "f", "g", "h", "j", "k", "l", "m"],
    ["w", "x", "c", "v", "b", "n"],
  ],

  // Begin-, kern- en eindstroken van het klik-klakboekje.
  clickBook: {
    begin: ["m", "k", "p", "r", "s", "v"],
    kern: ["a", "i", "aa", "oe", "oo", "ee"],
    einde: ["m", "k", "p", "s", "n", "t"],
  },

  // Nodig om automatisch MKM, MMKM enzovoort te herkennen.
  vowels: [
    "aa",
    "ee",
    "oo",
    "uu",
    "ie",
    "oe",
    "eu",
    "ui",
    "ei",
    "ij",
    "ou",
    "au",
    "a",
    "e",
    "i",
    "o",
    "u",
  ],

  // Langste combinaties worden in app.js altijd eerst gezocht.
  compoundGraphemes: [
    "sch",
    "oe",
    "aa",
    "ee",
    "oo",
    "uu",
    "ie",
    "ei",
    "ij",
    "ui",
    "eu",
    "ou",
    "au",
    "ng",
    "ch",
  ],

};
